root = "."
tmp_dir = "bin"

[build]
bin = "./cmd/main 8081"
cmd = "tailwindcss -i tailwind.css -o static/css/style.css && templ generate && cd cmd && go build main.go"
delay = 1000
exclude_dir = ["static"]
exclude_regex = [".*_templ.go"]
exclude_unchanged = false
include_ext = ["go", "tpl", "tmpl", "templ", "html"]
kill_delay = "0s"

[color]
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"
