#!/usr/bin/env sh
if [ $# -lt 1 ]; then
  >&2 echo "godly-stack-init projectname"
  exit 1
fi
git clone https://github.com/nimaaskarian/godly-stack "$1" || exit 1
cd "$1" || exit 1
rm -rf .git/
./init.sh "$1" && rm init.sh && cd ..

echo Your project is ready! now you might want to run:
echo cd "$1"
echo git init .
